// White-label configuration — auto-generated by scripts/merge.js
// Edit this file to override any values before building.

module.exports = {
  company: {
    name: "GEO 42",
    tagline: "The Answer Engine for Enterprise Brands",
    description: "GEO 42 is the AI visibility platform that makes your brand the definitive answer across every generative engine — ChatGPT, Perplexity, Gemini, and beyond.",
    industry: "AI Visibility & Generative Engine Optimization",
    founded: "2025",
  },
  author: {
    name: "",
    email: "hello@geo42.ai",
    jobTitle: "",
  },
  contact: {
    email: "hello@geo42.ai",
    phone: "",
    fax: "",
    url: "https://www.geo42.ai",
    address: {},
  },
  colors: {
    primary: "#0F0E0A",
    accent: "#D4A017",
  },
  fonts: {
    heading: "'Space Grotesk', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    body: "InterVariable, Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    mono: "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap",
  },
  siteUrl: "https://alexroessner.github.io/MagUpSite",
  pathPrefix: "/",
};
