// White-label configuration — auto-generated by scripts/merge.js
// Edit this file to override any values before building.

module.exports = {
  company: {
    name: "MagUp",
    tagline: "Content Marketing Brain for 1000+ Global Enterprises",
    description: "GEO + SEO Content Marketing platform that helps global enterprises efficiently acquire customers through AI-optimized content strategies. MagUp combines Generative Engine Optimization (GEO) with traditional SEO to maximize brand visibility across both AI answer engines and conventional search.",
    industry: "MarTech / AI-Powered Content Marketing",
    founded: "2025",
  },
  author: {
    name: "",
    email: "hello@magup.io",
    jobTitle: "",
  },
  contact: {
    email: "hello@magup.io",
    phone: "",
    fax: "",
    url: "https://www.magup.io",
    address: {},
  },
  colors: {
    primary: "#0D0D0D",
    accent: "#7C3AED",
  },
  fonts: {
    heading: "InterVariable, Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    body: "InterVariable, Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    mono: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap",
  },
  siteUrl: "https://alexroessner.github.io/MagUpSite",
  pathPrefix: "/",
};
